"use client";

import React from "react";
import Link from "next/link";
import { Scale, ShieldAlert, ArrowLeft, CheckCircle2, FileText } from "lucide-react";

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-white rounded-3xl p-8 sm:p-12 shadow-sm border border-slate-200 space-y-8">
        <div>
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-emerald-700 mb-4 transition-colors"
          >
            <ArrowLeft className="w-3.5 h-3.5" /> Back to Home
          </Link>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-50 border border-amber-200 flex items-center justify-center text-amber-700">
              <ShieldAlert className="w-5 h-5" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-slate-900">
                Statutory Legal Disclaimer & Regulatory Notice
              </h1>
              <p className="font-nastaliq text-sm text-emerald-800 font-bold mt-0.5">
                قانونی انتباہ اور دائرہ اختیار کی وضاحت
              </p>
            </div>
          </div>
        </div>

        <div className="prose prose-slate max-w-none text-xs leading-relaxed space-y-6 text-slate-700 border-t border-slate-100 pt-6">
          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <Scale className="w-4 h-4 text-emerald-700" />
              1. Non-Law Firm Self-Help Platform Status
            </h2>
            <p>
              Legal Saathi (LegalSaathi.pk) is an automated self-help legal document automation and AI educational platform operated by <strong>Nexvora Technologies</strong>. Legal Saathi is not a law firm, does not practice law in Pakistani courts, and does not provide formal legal representation or advocacy services as defined under the Legal Practitioners and Bar Councils Act 1973.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-700" />
              2. Compliance with Electronic Transactions Ordinance 2002 (ETO 2002)
            </h2>
            <p>
              All digital signatures, SHA-256 cryptographic tamper-evident hashes, and OTP audit trails generated by Legal Saathi are designed to conform to the evidentiary standards of the Electronic Transactions Ordinance 2002. However, legal instruments affecting rights over immovable property, powers of attorney, wills, and trusts may require physical attestation, Sub-Registrar registration, or e-Stamp paper printing under the Registration Act 1908 and Stamp Act 1899.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
              <FileText className="w-4 h-4 text-emerald-700" />
              3. Free Lawyer Review Terms
            </h2>
            <p>
              The "Free Lawyer Review" feature connects users with independent, licensed advocates of the High Court and District Bar Councils across Pakistan. Any opinions, annotations, or advice rendered by verified advocates represent the independent professional judgment of the individual practitioner and do not constitute legal liability on behalf of Legal Saathi platform operators.
            </p>
          </section>

          <div className="p-4 bg-emerald-50 rounded-2xl border border-emerald-200 text-[11px] text-emerald-900 font-medium">
            💡 For contested court litigation, criminal trial representation, or High Court constitutional petitions, users are strongly advised to engage an advocate of the High Court directly.
          </div>
        </div>
      </div>
    </div>
  );
}
